### ISSUE TITLE
Signup screen loading

### ISSUE THREAD

**Issue by 12tilak34** [Alpha17-2/Wave#26]
when i click on signup then it just keeps loading and don't go on next screen whats the issue ??

**Comment by Alpha17-2** [comment]
Hii @12tilak34 , Have you connected the app to Firebase ??

**Comment by 12tilak34** [comment]
@Alpha17-2 yes

**Comment by Alpha17-2** [comment]
@12tilak34 have you added the constants.dart file ??
Also you need to get the API url through Firebase realtime database and pase it into constants.dart file .

**Comment by 12tilak34** [comment]
@Alpha17-2 yes i have added the constant file and URL also

**Comment by Alpha17-2** [comment]
can you show me your constants.dart file ??

**Comment by 12tilak34** [comment]
https://www.mediafire.com/file/numljd0dbhmilbj/Screenshot+(10).png/file

**Comment by Alpha17-2** [comment]
![photo_2022-02-24_18-18-27](https://user-images.githubusercontent.com/57010722/155527215-20b8643e-cbe9-4279-905e-4acd2c85eb4b.jpg)
 
 You need to get the api from firebase realtime database.

**Comment by 12tilak34** [comment]
@Alpha17-2 do i need to have a billing account for that ??

**Comment by Alpha17-2** [comment]
No bro , dont worry about that . Its free .
Also Enable the following services :

1. Firebase realtime database
2. Firebase Firestore 
3. Firebase Authentication
4. Firebase Storage

All these services are free . Enjoy

**Comment by 12tilak34** [comment]
@Alpha17-2 wait let me try that

**Comment by Alpha17-2** [comment]
No

**Comment by 12tilak34** [comment]
solved thank you very much bro.. keep up the hard work !!

**Comment by Alpha17-2** [comment]
Thanks mate !! Please do star the repository if you like it 
Happy Fluttering !
