### ISSUE TITLE
there is a problem

### ISSUE THREAD

**Issue by rabee-abu-michael** [Alpha17-2/Wave#47]
Hi @Alpha17-2, There is a problem when I run the app from the terminal the app opens but with a white screen and nothing appears as shown in the picture
Please I want a solut
![1](https://user-images.githubusercontent.com/100477396/171029945-f5a29154-0b6e-480e-aeea-fda527d3b59c.PNG)
ion to this problem

**Comment by Alpha17-2** [comment]
@rabee-abu-michael Wave is an android application . It won't work on web

**Comment by rabee-abu-michael** [comment]
@Alpha17-2 
I want to run the app how

**Comment by Alpha17-2** [comment]
Run it on android emulator or physical device .

**Comment by rabee-abu-michael** [comment]
OK, thank you
