### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by Suleman-Elahi** [Alpha17-2/Wave#48]
Is it MIT or GPL?

I think choose one.

And if you are going with GPL then mention what someone has to do in order to use this app in production after white labelling it.

Good work btw.

**Comment by Alpha17-2** [comment]
What kind of production are you talking about?? Do you wish to publish the app to playstore after white labelling ?

**Comment by Suleman-Elahi** [comment]
>Do you wish to publish the app to playstore after white labelling ?

I don't but let's assume someone did what will happen?

**Comment by Alpha17-2** [comment]
To be honest , if anyone wants to do white labelling they can . I have no issues now . I deployed the app to play store in 2022. Now it has been taken down due to some reasons . 
So if anyone wants to white label the app and publish it they can , I hereby allow it . @Suleman-Elahi
